// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSqXw0B1h8hdeYIq-2kUYiR7h7htmTyl4',
    appId: '1:222814788040:web:258a8845b67bfff794c8fd',
    messagingSenderId: '222814788040',
    projectId: 'coffeeshop-6af4d',
    authDomain: 'coffeeshop-6af4d.firebaseapp.com',
    storageBucket: 'coffeeshop-6af4d.appspot.com',
    measurementId: 'G-88NRXC5MMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5v7SJr7buTfwHYC30x6jsKQmXjvOzyIg',
    appId: '1:222814788040:android:f98313739f6525d394c8fd',
    messagingSenderId: '222814788040',
    projectId: 'coffeeshop-6af4d',
    storageBucket: 'coffeeshop-6af4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBavBDiQKZTufL4GFnba0-QkKlf4Te8WwA',
    appId: '1:222814788040:ios:dee8d6d2f01fd9fa94c8fd',
    messagingSenderId: '222814788040',
    projectId: 'coffeeshop-6af4d',
    storageBucket: 'coffeeshop-6af4d.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );
}
